mysite/core/urls.py
from django.conf.urls import url
from . import auth_views, views, profile_views, order_views, search_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^register/$', auth_views.register, name='register'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^profile/$', profile_views.profile, name='profile'),
    url(r'^add_food$', profile_views.add_food, name='add_food'),
    url(r'^search$', search_views.search, name='search'),
    url(r'^online_orders$', order_views.online_order, name='online_order'),
    url(r'^online_orders/(\d{0,3})/$', order_views.online_order, name='online_order'),
    url(r'^offline_orders$', order_views.offline_order, name='offline_order'),
    url(r'^order_food$', order_views.order_food, name='order_food'),
    url(r'^edit_food/(\d{1,3})/$', profile_views.edit_food, name='edit_food'),
    url(r'^fetch_shop_items/(\d{1,3})/$', views.fetch_shop_items, name='fetch_shop_items'),
    url(r'^fetch_shop_profile/(\d{1,3})/$', views.fetch_shop_profile, name='fetch_shop_profile'),
    url(r'^$', views.home, name='home'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core.urls', namespace='core')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/core/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, _, PermissionsMixin
from django.db.models import ForeignKey

from .ModelHelper import MemberProfile, FoodHelper


class MemberManager(UserManager):
    pass


class Member(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'),
                              unique=True,
                              error_messages={
                                  'unique': _("A user with that email already exists."),
                              })

    name = models.CharField(_('name'), max_length=30)

    address = models.CharField(_('address'), max_length=200)
    type_of_food = models.CharField(max_length=1, choices=(
        ('T', 'Traditional'), ('F', 'Fast Food'), ('B', 'Traditional and Fast Food')))
    phone_numbers = models.CharField(max_length=11)
    brand_photo = models.ImageField(upload_to='images/')

    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin site.'))

    objects = MemberManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name',
                       'address', 'type_of_food',
                       'phone_numbers']

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def get_profile(self):
        return MemberProfile(str(self.name), str(self.address), str(self.phone_numbers),
                             str(self.brand_photo), self.pk)

    def __str__(self):
        return self.name


class Food(models.Model):
    restaurant = ForeignKey(Member)
    title = models.CharField(max_length=50)
    price = models.IntegerField()
    description = models.CharField(max_length=255)
    food_photo = models.ImageField(upload_to='images/')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'title' in kwargs:
            self.title = kwargs['title']
            self.price = kwargs['price']
            self.description = kwargs['description']
            self.food_photo = kwargs['food_photo']

    def get_food(self):
        return FoodHelper(str(self.title), str(self.price),
                          str(self.description), str(self.food_photo))

    def __str__(self):
        return self.title


class OnlineOrder(models.Model):
    restaurant = ForeignKey(Member)
    foods = JSONField('')
    total_price = models.IntegerField()
    order_date = models.DateField(auto_now_add=True)
    order_time = models.TimeField(auto_now_add=True)
    estimated_time = models.IntegerField(blank=True)
    customer = models.CharField(max_length=50)  # we just maintain an username
    handled = models.BooleanField(default=False)  # default = false && just for double check

    def __str__(self):
        return self.customer


class OfflineOrder(models.Model):
    restaurant = ForeignKey(Member)
    foods = JSONField('')
    order_date = models.DateField(auto_now_add=True)
    order_time = models.TimeField(auto_now_add=True)
    estimated_time = models.IntegerField()
    pending_time = models.IntegerField(blank=True)
    customer = models.CharField(max_length=50)
    rating = models.FloatField(null=True)

    def __str__(self):
        return self.order_date

mysite/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Member, Food


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for f in iter(self.fields):
            print(f)
            f = self.fields[f]
            if f.required:
                f.widget.attrs.update({'class': 'required'})

    class Meta:
        model = Member
        fields = (
            'email', 'name',
            'address', 'type_of_food',
            'phone_numbers'
        )
        help_texts = {

        }
        labels = {

        }

    def clean_foods(self):
        return self.cleaned_data['foods'] or None


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = (
            'name',
            'address', 'type_of_food',
            'phone_numbers', 'brand_photo'
        )
        help_texts = {

        }
        labels = {

        }


class UserFoodForm(forms.ModelForm):
    class Meta:
        model = Food

        fields = (
            'title', 'price',
            'description', "food_photo"
        )

mysite/core/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render

from .models import Member, Food


def home(request):
    if request.user.is_authenticated():
        foods = list(request.user.food_set.all())

        return render(request, 'core/home.html', {'foods': foods})

    return render(request, 'core/home.html')


def fetch_shop_items(request, pk=None):
    foods = list(Food.objects.filter(restaurant_id=pk))
    if foods:
        foods = [x.get_food().__dict__ for x in foods]
        return HttpResponse(json.dumps(foods), content_type="application/json")
    else:
        return HttpResponse('Sishti')


def fetch_shop_profile(request, pk=None):
    shop = Member.objects.filter(id=pk)
    if shop:
        shop = shop[0]
        return HttpResponse(json.dumps(shop.get_profile().__dict__), content_type="application/json")
    else:
        return HttpResponse('Sishti')

mysite/core/templates/core/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="body">
<div class="container-fluid">
    <figure>
        <img src="{% static 'home/logo.png' %}" width="300" height="200" alt="Waitech"
             title="Waitech"
             class="img-responsive" itemprop="image">
    </figure>
    <br><br>
    {% block body %}
    {% endblock %}
</div>
</body>

</html>

mysite/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% block title %} Home {% endblock %}

{% block body %}
<div class="jumbotron" align="center">
    {% if request.user.is_authenticated %}
    <span><h3 class="h3">Congrats. You are logged in as </h3>{{request.user.name}}</span>
    {% if user.brand_photo %}
    <figure>
        <img src="{{user.brand_photo.url}}" width="250" height="150"
             class="img-responsive">
    </figure>
    {% endif %}

    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'core:login' %}">Log in</a>
    <span class="h3">or</span>
    <a class="btn btn-lg btn-primary" href="{% url 'core:register' %}">Register</a>
    {% endif %}
</div>

<div id="best-deal">
    <div class="container">
        <div class="row">
            {% if request.user.is_authenticated %}

            {% for food in foods %}

            <div class="col-md-4 item-block animate-box" data-animate-effect="fadeIn" itemscope
                 itemtype="http://schema.org/Product">
                <div class="fh5co-property" itemscope itemtype="http://schema.org/Product">
                    {% if food.food_photo %}
                    <figure>
                        <img src="{{food.food_photo.url}}" width="300" height="200" alt="{{food.title}}"
                             title="{{food.title}}"
                             class="img-responsive" itemprop="image">
                    </figure>
                    {% endif %}

                    <div class="fh5co-property-innter">
                        <h3 itemprop="name"><a href="{% url 'core:edit_food' food.pk %}">{{food.title}}</a></h3>
                        <div class="price-status" itemprop="price">
                            <span class="price">${{food.price}} </span>
                        </div>
                        <p itemprop="description">{{food.description}}</p>
                    </div>
                </div>
            </div>

            {% endfor %}

            {% endif %}

        </div>
    </div>
</div>


{% endblock %}

mysite/core/templates/order/offline_order.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% block title %} offline order {% endblock %}

{% block body %}

<p>Some dummy contents also here.</p>
<p>Some dummy contents also here.</p>
<p>Some dummy contents also here.</p>
<p>Some dummy contents also here.</p>
<p>Some dummy contents also here.</p>
<p>Some dummy contents also here.</p>
<p>Some dummy contents also here.</p>

{% endblock %}

mysite/core/templates/order/online_order.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% block title %} online order {% endblock %}

{% block body %}

{% for order in order_list %}
    <p>{{ order.0 }} has ordered {{ order.1 }}
        for total price of : {{ order.0.total_price }} ,
        <a href="{% url 'core:online_order' forloop.counter0 %}"> Checkout</a>
    </p>
{% endfor %}

{% endblock %}

mysite/core/templates/profile/add_food.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% block title %} add food | {{ request.user.get_short_name }} {% endblock %}

{% block body %}

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <form method="post" enctype="multipart/form-data" action="{% url 'core:add_food' %}">

            {% csrf_token %}
            <div class="container-fluid">
                <div class="row">
                    {% bootstrap_form add_food_form %}
                </div>
                <div class="row">
                    <div class="well">
                        {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "done" %} Save
                        </button>
                        {% endbuttons %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

mysite/core/templates/profile/edit_food.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% block title %} Edit food {% endblock %}

{% block body %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <form method="post" enctype="multipart/form-data" action="{% url 'core:edit_food' food_to_edit.pk %}">

            {% csrf_token %}
            <div class="container-fluid">
                <div class="row">
                    {% bootstrap_form form %}
                </div>
                <div class="row">
                    <div class="well">
                        {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "done" %} Save
                        </button>
                        {% endbuttons %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mysite/core/templates/profile/profile.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% block title %} Change profile | {{ request.user.get_short_name }} {% endblock %}

{% block body %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <form method="post" enctype="multipart/form-data" action="{% url 'core:profile' %}">

            {% csrf_token %}
            <div class="container-fluid">
                <div class="row">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <span>Your profile</span>
                        </div>
                        <div class="panel-body">
                            <div style="width: 100%; display: table">
                                <div style="width: 85%; display: table-cell; vertical-align: middle">
                                    <div class="form-group">
                                        <label class="control-label" for="id_username">Username</label>

                                        <div class="form-control" id="id_username">{{ request.user.username }}</div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="id_email">Email address</label>

                                        <div class="form-control" id="id_email">{{ request.user.email }}</div>
                                    </div>
                                </div>
                            </div>
                            {% bootstrap_form profile_form %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="well">
                        {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "done" %} Save
                        </button>
                        {% endbuttons %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}